### ISSUE TITLE
Support code-davinci models

### ISSUE THREAD

**Issue by AsafMah** [SimiaCryptus/intellij-aicoder#26] opened 2023-03-05 06:39 UTC
When using any of the edit actions in python, the code never changes.
I tried different models.

Other languages work fine.

Appending code in python works fine.

But editing never changes the code.

**Comment by acharneski** [comment] 2023-03-06 03:57
Please provide some additional details, and if possible, screenshots.

Thanks!

**Comment by AsafMah** [comment] 2023-03-06 07:18
Figured out the issue.

It worked in Rider because I was on the "text-davinci-003"/"text-davinci-edit-001" models.

It didn't work in intellij because I was on "code-davinci-002"/"code-davinci-edit-001" models.

Is there a plan to support these? (since they are free for now?)

**Comment by acharneski** [comment] 2023-03-07 01:41
Same explanation as for your other issue; the model directory doesn't support use-case metadata yet.

I'm glad you got it working! Selecting alternate models is definitely "experimental" terrain. I consistently get the best results using the default setting of text davinci 3. Closing as it seems the issue is resolved.

**Closed by acharneski** 2023-03-07 01:41 UTC
